# @package _global_

defaults:
  - controller: target
  - scene: sh
  - color_corrector: nil
  - trainer: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: cmaes
  - _self_


hydra:
  job: 
    chdir: True
  sweep:
    dir: ${project}
    subdir: ${hydra.job.num}
 
  mode: MULTIRUN

  sweeper:
    sampler:
      seed: 42

    direction: maximize
    study_name: splat-trainer
    storage: null
    n_trials: 1000
    n_jobs: 1
    params:
      trainer.scene.parameters.log_scaling.lr: interval(0.001, 0.1)
      trainer.scene.parameters.rotation.lr: interval(0.001, 0.1)
      trainer.scene.parameters.alpha_logit.lr: interval(0.001, 0.1)
      trainer.scene.parameters.feature.lr: interval(0.001, 0.1)
      # trainer.scene.beta1: interval(0.5, 1)
      # trainer.scene.beta2: interval(0.7, 1)


trainer.optimizer: VisibilityAwareAdam

group_name: ${format:${hydra:job.num}}
project: optuna_multirun_${trainer.optimizer}_lr

optimize_algorithm: ${hydra:sweeper.sampler}

wait_exit: False
debug: False
