# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: tensorboard

hydra:
  job: 
    chdir: True


trainer:
  _target_: splat_trainer.trainer.TrainConfig
  output_path: null
  load_model: null

  device: "cuda:0"
  scene: 
    _target_: splat_trainer.scene.SceneConfig
    learning_rates:
      position:     0.0002
      log_scaling:  0.005
      rotation:     0.001
      alpha_logit:  0.05
      sh_feature:   0.005

    sh_ratio: 20.0

    # Initialisation from a point cloud
    num_neighbors: 3
    initial_alpha: 0.5
    sh_degree: 1
  
      
  iterations : 4000
  eval_iterations: 1000



debug: False

