# @package _global_

defaults:
  - _self_
  - dataset: scan

hydra:
  job: 
    chdir: True

logger:
  _target_: splat_trainer.logger.TensorboardLogger
  dir: log

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  output_path: null
  load_model: null

  device: "cuda:0"
  learning_rates: 
    _target_: splat_trainer.scene.LearningRates
    position: 0.001
    log_scaling: 0.005
    rotation: 0.001
    alpha_logit: 0.05

    base_sh: 0.0025
    higher_sh: 0.0002
      
  iterations : 4000
  eval_iterations: 1000

  num_neighbors: 3
  initial_alpha: 0.5

  sh_degree: 1


debug: False

