# @package _global_

defaults:
  - _self_
  - dataset: scan

logger:
  _target_: splat_trainer.logger.WandbLogger
  project: "splat-trainer"
  name: null

trainer:
  _target_: splat_trainer.TrainConfig
  
  load_model: null
  model_path: null

  device: "cuda:0"
  learning_rates: 
    _target_: splat_trainer.LearningRates
    position: 0.001
    log_scaling: 0.005
    rotation: 0.001
    alpha_logit: 0.05

    base_sh: 0.0025
    higher_sh: 0.0002
      
  iterations : 30000
  eval_iterations: 1000

  num_neighbors: 3
  initial_alpha: 0.5

  sh_degree: 1


debug: False

