# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: tensorboard

hydra:
  job: 
    chdir: True

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  output_path: null
  load_model: null

  device: "cuda:0"
  scene: 
    _target_: splat_trainer.scene.SceneConfig
    learning_rates:
      position:     0.00001
      log_scaling:  0.02
      rotation:     0.002
      alpha_logit:  0.1
      sh_feature:   0.005

    # scheduler:
    #   _target_: splat_trainer.scheduler.ExponentialDecay
    #   final_decay:  0.001
    #   warmup_steps: 0

    sh_ratio: 20.0

    # Initialisation from a point cloud
    num_neighbors: 5
    initial_alpha: 0.5
    initial_scale: 0.5
    sh_degree: 1


  controller:
    _target_: splat_trainer.scene.EMAConfig
    target_count: null

    # rate of splitting proportional to current size
    split_rate: 0.1

    # min visbility to be considered for splitting/pruning
    min_visibility: 20 
    decay_steps: 100.0 # in steps

  
  densify_interval: 20

  steps : 4000
  eval_steps: 1000

  ssim_weight: 0.0 # slower iteration but faster convergence
  ssim_scale: 0.5 # use ssim at a lower resolution (less computation)


wait_exit: False
debug: False

