# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: tensorboard
  - controller: target
  - scene: tcnn

  - trainer: default

hydra:
  job: 
    chdir: True

project: ???

wait_exit: False
debug: False

