# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: none
  - trainer: default
  - scene: mlp

  - controller: target
  - viewer: none
  - view_selection: random

hydra:
  job: 
    chdir: True

# filled in by command line overrides
project: ???
run_name: ???
base_path: ???

debug: False
training_scale: 1

far: 100.0
near: 0.1

normalize:
  _target_: splat_trainer.dataset.NormalizationConfig
  centering: True
  scaling_method: 'none'
  normalize_knn: 20

