# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: tensorboard
  - controller: target
  - scene: tcnn
  - color_corrector: nil
  - trainer: default

hydra:
  job: 
    chdir: True

# filled in by command line overrides
project: ???
run_name: ???
base_path: ???

debug: False

