# @package _global_

defaults:
  - _self_
  - dataset: scan
  - logger: tensorboard
  - controller: target
  - scene: tcnn

  - trainer: default

hydra:
  job: 
    chdir: True

# filled in by command line overrides
project: ???
run_name: ???
base_path: ???

wait_exit: False
debug: False

