# @package _global_

defaults:
  - logger: none
  - controller: target
  - scene: tcnn
  - trainer: default
  - test_datasets: default
  - color_corrector: nil
  - /hydra/callbacks:
    - average_result
  - override hydra/launcher: custom_rq
  - _self_


trainer:
  save_checkpoints: False
  save_output: False

  steps: 1000 # tiny number for testing

test_scene: ???

hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}/${hydra.job.num}__test_scene=${test_scene}
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
         - test_scene
  mode: MULTIRUN
  sweeper:
    params:
      # trainer.reg_loss_weight: choice([1, 1, 1], [0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1], [0, 1, 1])
      trainer.reg_loss_weight: choice([1, 1, 1], [0, 0, 0])
      # scene: sh, tcnn
      # color_corrector: nil, bilateral
      test_scene: bonsai, scan_1457_west, scan_21



wait_exit: False
debug: False
