# @package _global_

defaults:
  - logger: none
  - controller: target
  - scene: tcnn
  - trainer: default
  - test_datasets: default
  - color_corrector: nil
  - viewer: none
  - hydra/callbacks:
    - average_result
  - _self_


trainer:
  save_checkpoints: False
  save_output: False

  steps: 1000 # tiny number for testing


hydra:
  job:
    chdir: True
  sweep:
    dir: ${oc.env:HOME}/grid_search
    subdir: ${hydra.job.num}


  mode: MULTIRUN
  sweeper:
    params:
      +test_scene: scan_1457_east, scan_23, scan_1457_west
      # +test_scene: scan_1457_east, scan_23, bonsai, scan_1457_west, room, scan_21, bicycle, counter, flowers, garden, kitchen, stump, treehill

run_name: ${test_scene}


debug: False
