# @package _global_

defaults:
  - logger: none
  - controller: target
  - scene: mlp
  - trainer: default
  - test_datasets: default
  - _self_


trainer:
  save_checkpoints: False
  save_output: False

  steps: 1000 # tiny number for testing


hydra:
  job:
    chdir: True
  sweep:
    dir: ${oc.env:HOME}/grid_search
    subdir: ${hydra.job.num}


  mode: MULTIRUN
  sweeper:
    params:
      trainer.scene.learning_rates.position: 0.1, 0.05, 0.01
      +test_scene: bonsai, scan_1457_west, scan_21


debug: False
