# @package _global_

defaults:
  - logger: wandb
  - controller: target
  - scene: tcnn
  - trainer: default
  - test_datasets: default
  - color_corrector: nil
  - /hydra/callbacks:
    # - manage_rq_workers
    - average_result
  - override hydra/launcher: rq_launcher
  - _self_


trainer:
  save_checkpoints: False
  save_output: False

  steps: 20

test_scene: ???

worker_machines: lab3

hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: _${hydra.job.override_dirname}/${hydra.job.num}__test_scene=${test_scene}
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
         - test_scene
  mode: MULTIRUN
  sweeper:
    params:
      # trainer.reg_loss_weight: choice([1, 1, 1], [0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1], [0, 1, 1])
      scene: sh, tcnn
      # trainer.reg_loss_weight: choice([1,0,0], [0,0,1], [1,1,0], [0,1,1])
      # color_corrector: nil, bilateral
      test_scene: bonsai, scan_21
      # test_scene: bonsai, scan_1457_west, scan_21, bicycle, counter, flowers, garden, kitchen, room, stump, treehill, scan_1457_east, scan_23
      # test_scene: scan_21, scan_1457_west, treehill, kitchen, counter, flowers, bonsai, scan_23, room

project: ${sanitize:${hydra:sweep.dir}}
run_name: ${hydra:job.num}__${simplify:${hydra:job.override_dirname}}__${test_scene}

wait_exit: False
debug: False
