# @package _global_

defaults:
  - logger: wandb
  - controller: target
  - scene: sh
  - trainer: default
  - test_datasets: default
  - color_corrector: nil
  - viewer: none
  - hydra/callbacks:
    - manage_rq_workers
    - average_result
  - override hydra/launcher: rq
  - _self_


trainer:
  save_checkpoints: False
  save_output: False

  steps: 1000


test_scene: ???

worker_machines: test

hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${run_name:${hydra:overrides.task}}_/${hydra.job.num}__test_scene=${test_scene}
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
         - test_scene
  mode: MULTIRUN
  sweeper:
    params:
      # test_scene: scan_1457_east, scan_23, bonsai, scan_1457_west, room, scan_21, bicycle, counter, flowers, garden, kitchen, stump, treehill
      test_scene: scan_23, scan_1457_west, scan_1457_east

optimize_algorithm: grid_search

project: ${sanitize:${hydra:sweep.dir}}__${project_name:${hydra:overrides.task}}
group_name: ${group_name:${hydra:overrides.task}}
run_name: ${conditional_run_name:${optimize_algorithm},${group_name},${format:${hydra:job.num}},${run_name:${hydra:overrides.task}}}



debug: False
