# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  load_model: null

  device: "cuda:0"

  lr_scheduler:
    _target_: splat_trainer.scheduler.ExponentialDecay
    base_lr: 1.0
    final_lr:  0.1
    warmup_steps: 0


  steps : 20000
  eval_steps: 2000

  # Initialisation from a point cloud
  num_neighbors: 5
  initial_alpha: 0.5
  initial_point_scale: 0.5

  max_initial_points: null
  background_points: 0

  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  ssim_scale: 1.0 # use ssim at a lower resolution (less computation)

  scale_reg: 100.
  opacity_reg: 0.01

  blur_cov: 0.3
  antialias: True

  raster_config: 
    _target_: taichi_splatting.RasterConfig



