# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  load_model: null

  device: "cuda:0"

  lr: ${log_linear:1.0,0.1}


  steps : 20000
  eval_steps: 2000

  save_checkpoints: False
  save_output: True

  # Initialisation from a point cloud
  num_neighbors: 5
  initial_alpha: 0.5
  initial_point_scale: 0.1

  initial_points: 50000
  add_initial_points: False  # if true, add extra random points to the point cloud
  load_dataset_cloud: True  # if false, use a random point cloud

  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  ssim_scale: 1.0 # use ssim at a lower resolution (less computation)


  scale_reg: 0.1
  opacity_reg: 0.01

  blur_cov: 0.3 # only used if antialias is false
  antialias: True
  
  densify_interval: 100


  raster_config: 
    _target_: taichi_splatting.RasterConfig



