# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig

  # These need to be defined elsewhere
  scene: ???
  controller: ???
  view_selection: ???

  # Point cloud initialization settings
  cloud_init:
    _target_: splat_trainer.trainer.CloudInitConfig

    # initial scale is (mean distance to num_neighbors) * initial_point_scale
    num_neighbors: 5
    initial_point_scale: 0.2
    initial_alpha: 0.2

    initial_points: 200_000  
    limit_points: 100_000

    clamp_near: 1.0
    min_view_overlap: 4 # minimum number of views a point must be visible in when adding random points

  # Scheduling settings
  total_steps: ${int_mul:20000,${training_scale}}
  eval_steps: ${int_mul:2000,${training_scale}}
  log_interval: 10

  # target point cloud size 
  target_points: ${int_mul:1000000,${training_scale}}


  # Evaluation settings
  num_logged_images: 8
  log_worst_images: 2


  # Add detailed histogram logging for debug purposes
  log_details: False


  # Early stopping settings

  # Maximum (average) time for a training step, if exceeded over 10 log_intervals training will be aborted
  min_step_rate: 10.0 # steps per second
  max_ssim_regression: 0.01 # if ssim regression exceeds this value, training will be aborted

  # Loss function settings
  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  # l1_weight: 1.0
  mse_weight: 10.0
  ssim_levels: 3

  # view similarity
  vis_clusters: 1024

  # renderer settings
  antialias: False
  blur_cov: 0.3 # only used if antialias is false

  # General settings
  device: "cuda:0"

  # Save intermediate checkpoints (can generate a lot of data)
  save_checkpoints: False

  # If false, disables saving any outputs (initial point cloud, cameras, output cloud etc.)
  save_output: True  

  # If false, disables logging any images to logger
  log_images: True


# If true, enables progress bars - if false, disables all progress bars which polute log files 
interactive: True

training_scale: 1
test_every: 8

far: 100.0
near: 0.1

normalize:
  _target_: splat_trainer.dataset.NormalizationConfig
  centering: True
  scaling_method: 'none'
  normalize_knn: 20


