# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig

  # These need to be defined elsewhere
  scene: ???
  controller: ???
  view_selection: ???

  # Point cloud initialization settings
  cloud_init:
    _target_: splat_trainer.trainer.CloudInitConfig
    num_neighbors: 5
    initial_alpha: 0.2
    initial_point_scale: 0.2

    initial_points: null  
    limit_points: null

    min_point_overlap: 8 # minimum number of views a point must be visible in when adding random points



  # Scheduling settings
  total_steps: ${int_mul:20000,${training_scale}}
  eval_steps: ${int_mul:2000,${training_scale}}
  log_interval: 10

  # target point cloud size 
  target_points: ${int_mul:1000000,${training_scale}}


  # Evaluation settings
  num_logged_images: 8
  log_worst_images: 2

  log_details: False

  # Loss function settings
  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  # l1_weight: 1.0
  mse_weight: 10.0
  ssim_levels: 3

  scale_reg: ${log_decay:0.01, 0.001}
  opacity_reg: ${log_decay:0.001, 0.001}
  # aspect_reg: 0.0001

  # view similarity
  vis_clusters: 1024

  # renderer settings
  antialias: False
  blur_cov: 0.3 # only used if antialias is false

  # General settings
  device: "cuda:0"
  save_checkpoints: False
  save_output: True






