# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  load_model: null

  device: "cuda:0"

  steps : ${int_mul:20000,${training_scale}}
  eval_steps: ${int_mul:2000,${training_scale}}

  save_checkpoints: False
  save_output: True

  # Initialisation from a point cloud
  num_neighbors: 5
  initial_alpha: 0.2
  initial_point_scale: 0.5

  initial_points: 200000
  limit_points: null
  
  add_initial_points: False  # if true, add extra random points to the point cloud
  load_dataset_cloud: True  # if false, use a random point cloud

  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  l1_weight: 1.0
  ssim_levels: 4

  scale_reg: ${log_decay:1.0, 0.1}
  opacity_reg: ${log_decay:0.1, 0.01}
  
  aspect_reg: 0.0

  blur_cov: 0.3 # only used if antialias is false
  antialias: False

  densify_interval: 
    _target_: splat_trainer.config.Piecewise
    start: 50
    steps:
      - [0.2, 100]
      - [0.5, 100]
    
    scale: ${training_scale}



  raster_config: 
    _target_: taichi_splatting.RasterConfig





