# @package _global_

trainer:
  _target_: splat_trainer.trainer.TrainConfig
  load_model: null

  device: "cuda:0"

  steps : 20000
  eval_steps: 2000

  save_checkpoints: False
  save_output: True

  # Initialisation from a point cloud
  num_neighbors: 5
  initial_alpha: 0.5
  initial_point_scale: 0.1

  initial_points: 50000
  limit_points: null
  
  add_initial_points: False  # if true, add extra random points to the point cloud
  load_dataset_cloud: True  # if false, use a random point cloud

  ssim_weight: 1.0 # ssim is expensive but converges faster than just l1 loss
  l1_weight: 1.0
  ssim_levels: 4

  scale_reg: 0.1
  opacity_reg: ${log_linear:1.0,0.01}
  aspect_reg: 0.01

  blur_cov: 0.3 # only used if antialias is false
  antialias: False

  densify_interval: 
    _target_: splat_trainer.config.Piecewise
    start: 100
    steps:
      - [0.2, 200]
      - [0.5, 400]

  raster_config: 
    _target_: taichi_splatting.RasterConfig



