# @package _global_

dataset:
  _target_: splat_trainer.dataset.COLMAPDataset
  base_path: ???

  model_dir: "sparse/0"
  image_dir: "images"

  image_scale: null
  resize_longest: 1536
  test_every: ${test_every}

  depth_range: 
    - ${near}
    - ${far}


# hydra:  
#   run:
#     dir: ${scan_name:${dataset.scan_file}}  