# @package _global_

dataset:
  _target_: splat_trainer.dataset.COLMAPDataset
  base_path: ???

  model_dir: "sparse/0"
  image_dir: "images"

  image_scale: null
  resize_longest: 1536
  val_stride: 0

  depth_range: [0.1, 100.0]



# hydra:  
#   run:
#     dir: ${scan_name:${dataset.scan_file}}  