# @package _global_

scan_name: ${without_ext:${basename:${dataset.scan_file}}}
model_path: ${dirname:${dataset.scan_file}}/gaussian_${scan_name}


dataset:
  _target_: splat_trainer.scan.ScanDataset
  scan_file: ${..scan_file}

  image_scale: 1.0
  val_count: 10

  depth_range: [0.1, 100.0]





trainer:
  model_path: ${..model_path}
