# @package _global_


dataset:
  _target_: splat_trainer.ScanDataset
  scan_file: ${..scan_file}

  image_scale: 0.5
  val_count: 10

scan_dir: ${dirname:${dataset.scan_file}}


trainer:
  output_model_dir: ${..scan_dir}/gaussian
  output_log_dir: ${..scan_dir}/gaussian