# @package _global_

dataset:
  _target_: splat_trainer.dataset.ScanDataset
  scan_file: ???

  image_scale: 1.0
  val_stride: 0

  depth_range: [0.1, 100.0]



# hydra:  
#   run:
#     dir: ${scan_name:${dataset.scan_file}}  