# @package _global_

dataset:
  _target_: splat_trainer.dataset.ScanDataset
  scan_file: ???

  image_scale: null
  resize_longest: 1536
  val_stride: 0

  depth_range: 
    - ${near}
    - ${far}


# hydra:  
#   run:
#     dir: ${scan_name:${dataset.scan_file}}  