# @package _global_

logger:
  _target_: splat_trainer.logger.WandbLogger
  entity: UCVision
  project: ${..project}
  name: ${..run_name}
  # group: ${group_name:${hydra:job.override_dirname}}
  group: ${group_name:${hydra:overrides.task}}
  
