# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.MCMCConfig
    noise_level: ${log_decay:100.0, 0.001}
    opacity_threshold: 0.1

  # opacity_reg: ${log_decay:0.001, 0.01}
  
  # scale_reg: ${log_decay:0.1, 0.001}
