# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.MCMCConfig
    noise_level: ${log_decay:100.0, 0.01}
    opacity_threshold: 0.1

  opacity_reg: ${log_decay:0.001, 100.0}
  
