# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size
    split_rate: 0.01

    # min visbility to be considered for splitting/pruning
    min_visibility: 20 
  
  densify_interval: 20