# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size
    prune_rate: 0.05

    # min visbility to be considered for splitting/pruning
    alpha: 0.1
  