# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size
    prune_rate: 0.025

    # min visbility to be considered for splitting/pruning
    split_alpha: 0.99
    prune_alpha: 0.1

    # threshold (of screen width) for pruning large points
    max_scale: 0.25
  