# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size
    prune_rate: 0.05

    # minimum number of times point is in view before it is able to be pruned
    min_views: 10

    # threshold (of screen width) for pruning large points
    max_scale: 0.4
    
  