# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size (per 100 steps)
    prune_rate: 0.075

    densify_interval: ${..densify_interval} # take from trainer config

    # min visbility to be considered for splitting/pruning
    ema_half_life: 50 
  
