# @package _global_

trainer:
  controller:
    _target_: splat_trainer.controller.TargetConfig
    
    target_count: 1000000

    # rate of splitting proportional to current size
    prune_rate: 0.15

    # min visbility to be considered for splitting/pruning
    ema_half_life: 50 
  
  densify_interval: 400