# @package _global_

trainer:
  color_corrector: 
    _target_: splat_trainer.color_corrector.BilateralCorrectorConfig

    device: ${..device}
    steps: ${..steps}
    bilateral_grid_shape: [16, 16, 8]