# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.SHConfig
    parameters:
      position:
        lr: ${log_decay:0.1, 0.25}
        type: local_vector

      log_scaling:
        lr: 0.03

      rotation:
        lr: 0.01

      alpha_logit:
        lr: 0.05

      feature:
        lr: 0.02


    beta1: 0.9
    beta2: 0.999

    sh_ratio: 20.0
    sh_degree: 3


