# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.SHConfig
    learning_rates:
      position:     0.00001

      log_scaling:  0.02
      rotation:     0.0025
      alpha_logit:  0.025
      feature:   0.001

    sh_ratio: 20.0
    sh_degree: 2


