
# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.TCNNConfig

    parameters:
      position:
        lr: ${log_decay:0.1, 0.1}
        type: local_vector

      log_scaling:
        lr: 0.03

      rotation:
        lr: 0.01

      alpha_logit:
        lr: 0.05

      feature:
        lr: 0.5
        type: vector


    beta1: 0.9
    beta2: 0.999

    # TCNN specific
    image_features: 16
    point_features: 16

    hidden_features: 64
    affine_color_model: False

    layers: 3

    # Per image features (as opposed to per-camera features)
    per_image: True

    lr_image_feature: 0.1
    lr_nn: 0.0002


