
# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.TCNNConfig

    learning_rates:
      position:     0.00001
      log_scaling:  0.02
      rotation:     0.0025
      alpha_logit:  0.05
      feature:   0.1


    # TCNN specific
    image_features: 8
    point_features: 8

    hidden: 32
    layers: 4

    lr_image_feature: 0.00001
    lr_nn: 0.00001


