
# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.TCNNConfig

    parameters:
      position:
        lr: ${log_decay:0.5, 0.2}
        type: local_vector

      log_scaling:
        lr: 0.1

      rotation:
        lr: 0.01
        type: vector

      alpha_logit:
        lr: 0.1

      feature:
        lr: 5.0
        type: vector


    beta1: 0.8
    beta2: 0.95

    vis_beta: 0.999

    # TCNN specific
    image_features: 48
    point_features: 16

    hidden_features: 64
    hidden_layers: 1

    sh_degree: 5

    # Per image features (as opposed to per-camera features)
    per_image: True

    lr_image_feature: 2.0
    lr_nn: ${log_decay:0.003, 0.1}


