
# @package _global_

trainer:
  scene: 
    _target_: splat_trainer.scene.TCNNConfig

    learning_rates:
      position:     0.05
      log_scaling:  0.01
      rotation:     0.0025
      alpha_logit:  0.025
      feature:   0.05


    beta1: 0.8
    beta2: 0.999

    # TCNN specific
    image_features: 16
    point_features: 16

    hidden: 32
    layers: 3

    # Per image features (as opposed to per-camera features)
    per_image: True

    lr_image_feature: ${log_linear:0.1, 0.01}
    lr_nn: 0.0002


