# @package _global_


hydra:
  callbacks:
    manage_rq_workers:
      _target_: splat_trainer.multirun.manage_rq_worker.ManageRQWorkers
      config_file: test
      flask_port: 8000
      redis_port: 6379
      get_pass: False

    average_result:
      _target_: splat_trainer.multirun.average_result.AverageResult
      output_dir: ${hydra.sweep.dir}
      sweep_params: ${hydra.sweeper.params}