# @package _global_

trainer:
  view_selection:
    _target_: splat_trainer.trainer.TargetOverlapConfig
    batch_size: 1

    # Temperature threshold - higher is more random
    overlap_temperature: 0.5
    history_size: 4

    # Select overlap values closest to target
    target_overlap: 0.25